# ui page

# loading library
library(plotly)
library(ggplot2)
library(shiny)

source("A5_server.R")

# loading data
data <- read.csv("http://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv", stringsAsFactors = F)

# first page
page_one <- tabPanel(
  "Introduction",
  h2("Introduction"),
  p("Do you know what your carbon footprint is? 
    Here, we will reflect on the amount of greenhouse gases that are generated by our actions, also known as our carbon footprint.
    More specifically, we will focus on the impact of various fossil fuels, like gas, oil, and coal, and their impact on climate change. 
    We will closely examine the different fossil fuels and their negative impact on the climate over the years."),
  h2("Three Relevant Values of Interest"),
  p(em(strong("Which continent has the greatest amount of CO2 emission?"))),
  p(em(strong("What was the CO2 emission trend in the year 1750?"))),
  p(em(strong("What was the CO2 emission trend in the year 2000?"))),
)

# second page
page_two <- tabPanel(
  h2("Fossil Fuel Emissions"),
  sidebarLayout(
    sidebarPanel(
      selectInput(
        inputId = "climate_type",
        label = "Type of Fossil Fuel",
        choices = c("gas_co2", "oil_co2", "coal_co2")
      ),
      selectInput(
        inputId = "color_input",
        label = "Pick a color",
        choices = c("Blue", "Red", "Purple")
      ),
      sliderInput(
        inputId = "restrict",
        label = "Years", min = 1750, max = 2020, value = c(1750, 2020)
      )
    ),
    mainPanel(
      plotlyOutput(outputId = "climate_output"),
      h4("Fossil Fuel Emissions Chart Summary"),
      p("Above is an interactive chart that allows users to select the type of fossil fuel to view its impact on the environment. 
        In addition to the selection between gas, oil, and coal, users are able to pick a between the colors blue, red and purple to display the chart. 
        Lastly, users are able slider bar to view various points in times over the years 1750 and 2020. 
        From this interactive chart, we can conclude that fossil fuel emissions have increased as a whole over the years. 
        In an attempt to prevent climate change and polluting the environment, we must be more aware of the products we use and the CO2 emissions these products release.")
    )
  )
)

ui <- navbarPage(
  tags$title("Climate Change by Surina Soumpholphakdy"),
  page_one,
  page_two,
  includeCSS("style.css")
)
